name: mbuild-binder

channels:
  - anaconda
  - omnia
  - janschulz
  - bioconda

dependencies:
  - python=3.4
  - numpy
  - scipy
  - mdtraj
  - packmol
  - nglview=0.5.1
  - oset
  - networkx
  - parmed
  - ipyext
  - traitlets=4.2.1
  - ipywidgets==4.1.1
  - notebook=4.1.0
  - pip:
    - git+https://github.com/imodels/mbuild.git#egg=mbuild[complete]